os: linux
dist: bionic
language: python
python: "2.7"

git:
  depth: false

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

before_install:
  - sudo echo "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/ /" | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
  - curl -L https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_18.04/Release.key | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get install -y podman

install:
  # Install ansible
  - pip install ansible ansible-lint molecule[podman]

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./' >ansible.cfg

script:
  # Lint test
  - ansible-lint tests/test.yml
  # Run the role in a molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
