os: linux
language: python
python: "2.7"

git:
  depth: false

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

services:
  - docker

before_install:
  - sudo docker pull docker.io/tripleomaster/centos-binary-qdrouterd:current-tripleo-rdo

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-lint tests/test.yml
  # Run the role
  - ansible-playbook tests/test.yml -i tests/inventory --extra-vars "qdr_conf_output_dir=`pwd`/output" && cat `pwd`/output/qdrouterd.conf
  - sudo docker run -dti --name qdr-test --net=host -v "`pwd`/output/qdrouterd.conf:/etc/qpid-dispatch/qdrouterd.conf" -v "`pwd`/output:/var/log/qdrouterd" -v /var/run:/var/run -v /tmp:/tmp -v "`pwd`/tests/kolla_config_files/:/var/lib/kolla/config_files/" -e KOLLA_CONFIG_STRATEGY=COPY_ALWAYS tripleomaster/centos-binary-qdrouterd:current-tripleo-rdo
  - sudo docker logs qdr-test
  - sudo docker exec qdr-test qdstat -b 0.0.0.0:5666 -l

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
