os: linux
language: python
python: "2.7"

git:
  depth: false

# Install ansible
addons:
  apt:
    update: true
    packages:
      - python-pip

services:
  - docker

before_install:
  - sudo docker pull docker.io/tripleomaster/centos-binary-qdrouterd:current-tripleo-rdo

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Lint test
  - ansible-lint tests/test.yml
  # Run the role in a molecule test
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
