---
driver:
  name: podman
platforms:
  - name: qdrtest
    image: docker.io/tripleomaster/centos-binary-qdrouterd:current-tripleo-rdo
provisioner:
  name: ansible
  log: true
verifier:
  name: ansible

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
    - cleanup
